name: .NET

on:
  push:
    branches: [ feex ]
  pull_request:
    branches: [ feex ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest
    - name: Build Dalamud
      run: |
        cd ..
        git clone https://github.com/goatcorp/Dalamud.git --recursive
        cd Dalamud
        nuget restore Dalamud.sln
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\..\Dalamud\Dalamud.sln /t:Build /p:Configuration=Release /p:DefineConstants=XL_NOAUTOUPDATE
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
